dist: xenial
notifications:
  email: false
language: python
python:
- 3.5
- 3.6
- 3.7
- pypy3.5
install:
- pip install -U tox-travis
- pip install -e .[dev]
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: nKY/Hufrni0fk1wjnlcakWx4tFVdw/8XZJmj/vs6SDz35CBcdm+aABImUg47kZq0+ebNghzu7hL/164es6XTtl1QtHh8V+7dzk+e/cKHYUYlcgCQnBUSESdfXAavm7Q/JVzhn5fCe9IACHQ7hiwp38uNZPT2NsPMnvEXZMvbLPnmumVB5YGCFTebB8XrG8aOVLR2g6orA6nAVo04X3h+O5WppDn31wPeRnHRobV9p+K1ik63jyvbeJ+cuSwrtfBY6oiYjIliw6Gz2tn5mvpE0+qDDI1ABvVI2mjoGvXb6np2XQRBCTzTDm/EUQo5Ew1E5hzTSv/RNYSqjPsOajxOvFxuF5JCIvGnZGkLxY4G9MvSmm3GCcfuOQePDTyXQMrLFJIp7jd60W87wb8dLZlDw3jp9H3UpikrhJGtRAg5CGAkaS56TgF2ip333qETuam0zw7F9V4CqngcM8tUyBXi8HnYF5Lzt3kUyPuKK8dMkfDgXyeE/XSpsp4FTE2xG2YSAnp0YsJRQpVl84ovuupUI3rCQwYODfOM8RtK4UoTH7Csj1zAJ4LuHuTR7pzSFa9r87miQ3HHmZUVCSNmfvA7l81jsi+59d371T5D2HD+w2PqHziExL3TYklcgLRZ5kX2ImRfhjMgTJOeOX96dIx4JzFAFzvP/5zWTGmUYJ8vnP0=
  on:
    tags: true
    branch: master
    python: 3.6
